# INX FUTURE INC EMPLOYEE PERFORMANCE - DATA PROCESSING

## 1. INTRODUCTION
## 2. PROJECT OBJECTIVE
## 3. DATASET LOADING
## 4. DATASET OVERVIEW
## 5. DATA STRUCTURE AND DATA TYPES
## 6. DATA QUALITY ASSESSMENT
## 7. MISSING VALUE ANALYSIS
## 8. DUPLICATE RECORD ANALYSIS
## 9. TRAGET VARIABLE VALIDATION
## 10. DATA CLEANING
## 11. FEATURE IDENTIFICATION
## 12. PROCESSED DATASET CREATION
## 13. DATA PROCESSING SUMMARY
## 14. CONCLUSION

# INX Future Inc Employee Performance - Data Processing

## 1. INTRODUCTION

INX Future Inc is an organization that aims to understand the factors incfluencing employee performance. Employee performance can be affected by serval factors such as department, job role, education, experience, salary, working environment, job satisfaction, training, work-life balance, and other organizational attributes.

The purpose of this notebook is to prepare the employee performance dataset for further exploratory data analysis and machine learning. The data processing stage focuses on understanding the dataste, checking its quality, identifying missing and duplicate records, validating the traget variable, removing irrelevant features, and creating a clean processed dataset.

Data preprocessing is an important stage in a machine learning project because the quality of the input data directly affects the reliabilty of the analysis and model performance. Therefore, this notebook systematically examines the structure, completeness, consistency, and suitability of the dataset before modeling.

### Insight

The purpose of this notebook is convert the raw employee dataset into a clean and reliable dataset that can be used for futher analysis and machine learning.

## 2. PROJECT OBJECTIVE

The main objective of this project is to analyze employee performance data and identify the important factors associated with employee performance. This project will use data preprocessing, EDA, statistical analysis, visualization, and machine learning techniques.

The specific objectives of the data preprocessing stage are to lead the raw dataset, understand its structure, assess data quality, identify missing duplicate records, validate the target variable, remove irrelevant or identifier columns, and create a processed dataset suitable for subsequent machine learning tasks.

### 2.1 Import Libraries

In [1]:
# Import required libraries

import os
import pandas as pd
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.

### Insight

Pandas is used for data loading and manipulation, NumPy is used for numerical operations, and OS is used to manage file paths and director

## 3. DATASET LOADING

The first step is to load the raw employee performance dataset into a Pandas DataFrame. The raw dataset should be stored inside the `data/raw` directory of the project structure.

Keeping the original dataset in the raw-data folder is imporatnt because the original source data should remain unchanged. All cleaning and transformation operations sholud be performed on a separate DataFrame, and final processed dataset should be saved in the `data/processed` directory.

In [2]:
# Define project paths

project_name =  r"E:\IABAC\INX_Future_Inc_Employee_Performance"

raw_path = os.path.join(
    project_name,
    "data",
    "raw"
)

processed_path = os.path.join(
    project_name,
    "data",
    "processed"
)

print(f"Raw data folder: {raw_path}")
print(f"Processed data folder: {processed_path}")

Raw data folder: E:\IABAC\INX_Future_Inc_Employee_Performance\data\raw
Processed data folder: E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed

### 3.1 Check Raw Files

In [3]:
# Display files avaiable in the raw data folder

if os.path.exists(raw_path):

    raw_files = os.listdir(raw_path)

    print(f"Number of files found in raw folder: {len(raw_files)}")
    print(f"Files available :{raw_files}")

else:

    print(f"Raw data folder does not exist: {raw_path}")

Number of files found in raw folder: 1
Files available :['INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls']

### 3.2 Dataset is Excel

In [4]:
# Dataset loading in Excel

file_name = "INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls"

file_path = os.path.join(
    raw_path,
    file_name,
)

df = pd.read_excel(file_path)

print(f"Dataset loaded successfully.")
print(f"Dataset path : {file_path}")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Dataset loaded successfully.
Dataset path : E:\IABAC\INX_Future_Inc_Employee_Performance\data\raw\INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls
Number of rows: 1200
Number of columns: 28

### 3.3 Create Working Copy

In [5]:
# Create a working copy of the original dataset

df_processed = df.copy()

print(f"Original dataset shape: {df.shape}")
print(f"Working dataset shape: {df_processed.shape}")

Original dataset shape: (1200, 28)
Working dataset shape: (1200, 28)

### Insight

The raw dataset has been loaded successfully and a separate working copy been created. The original DataFrame is preserved so that the preprocessing steps can tracked back to the original data if required.

### 4. DATASET OVERVIEW

A basic dataset overview helps determine the size the size of the dataset and provides an initial understand of the available employee records and attributes. The number of rows represents employee records, while the number of columns represents employee-relates features and target variable.

### 4.1 Display First Five Records (Head)

In [6]:
# Display first five records

print("First 5 records:")

display(df_processed.head())

print(f"Number of records: {df_processed.shape[0]}")
print(f"Number of features/columns: {df_processed.shape[1]}")

First 5 records:

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

Number of records: 1200
Number of features/columns: 28

### 4.2 Dispaly Last Five Records (Tail)

In [7]:
# Display last five records

print("Last 5 Records:")

display(df_processed.tail())

Last 5 Records:

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
1195,E100992,27,Female,Medical,Divorced,Sales,Sales Executive,Travel_Frequently,3,1,...,2,6,3,3,6,5,0,4,No,4
1196,E100993,37,Male,Life Sciences,Single,Development,Senior Developer,Travel_Rarely,10,2,...,1,4,2,3,1,0,0,0,No,3
1197,E100994,50,Male,Medical,Married,Development,Senior Developer,Travel_Rarely,28,1,...,3,20,3,3,20,8,3,8,No,3
1198,E100995,34,Female,Medical,Single,Data Science,Data Scientist,Travel_Rarely,9,3,...,2,9,3,4,8,7,7,7,No,3
1199,E100998,24,Female,Life Sciences,Single,Sales,Sales Executive,Travel_Rarely,3,2,...,1,4,3,3,2,2,2,0,Yes,2

### 4.3 Display dataset dimensions (Shape)

In [8]:
# Display dataset dimensions

rows, columns = df_processed.shape

print(f"Total number of rows: {rows}")
print(f"Total number of columns :{columns}")

Total number of rows: 1200
Total number of columns :28

### 4.4 Display Statistical Summary (Describe)

In [9]:
# Didpaly statistical summary

display(df_processed.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
EmpNumber,1200,1200,E1001000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,1200.0,NaN,NaN,NaN,36.918333,9.087289,18.0,30.0,36.0,43.0,60.0
Gender,1200,2,Male,725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EducationBackground,1200,6,Life Sciences,492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MaritalStatus,1200,3,Married,548,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmpDepartment,1200,6,Sales,373,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmpJobRole,1200,19,Sales Executive,270,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BusinessTravelFrequency,1200,3,Travel_Rarely,846,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DistanceFromHome,1200.0,NaN,NaN,NaN,9.165833,8.176636,1.0,2.0,7.0,14.0,29.0
EmpEducationLevel,1200.0,NaN,NaN,NaN,2.8925,1.04412,1.0,2.0,3.0,4.0,5.0
EmpEnvironmentSatisfaction,1200.0,NaN,NaN,NaN,2.715833,1.090599,1.0,2.0,3.0,4.0,4.0
EmpHourlyRate,1200.0,NaN,NaN,NaN,65.981667,20.211302,30.0,48.0,66.0,83.0,100.0
EmpJobInvolvement,1200.0,NaN,NaN,NaN,2.731667,0.707164,1.0,2.0,3.0,3.0,4.0
EmpJobLevel,1200.0,NaN,NaN,NaN,2.0675,1.107836,1.0,1.0,2.0,3.0,5.0
EmpJobSatisfaction,1200.0,NaN,NaN,NaN,2.7325,1.100888,1.0,2.0,3.0,4.0,4.0
NumCompaniesWorked,1200.0,NaN,NaN,NaN,2.665,2.469384,0.0,1.0,2.0,4.0,9.0
OverTime,1200,2,No,847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmpLastSalaryHikePercent,1200.0,NaN,NaN,NaN,15.2225,3.625918,11.0,12.0,14.0,18.0,25.0
EmpRelationshipSatisfaction,1200.0,NaN,NaN,NaN,2.725,1.075642,1.0,2.0,3.0,4.0,4.0
TotalWorkExperienceInYears,1200.0,NaN,NaN,NaN,11.33,7.797228,0.0,6.0,10.0,15.0,40.0
TrainingTimesLastYear,1200.0,NaN,NaN,NaN,2.785833,1.263446,0.0,2.0,3.0,3.0,6.0
EmpWorkLifeBalance,1200.0,NaN,NaN,NaN,2.744167,0.699374,1.0,2.0,3.0,3.0,4.0
ExperienceYearsAtThisCompany,1200.0,NaN,NaN,NaN,7.0775,6.236899,0.0,3.0,5.0,10.0,40.0
ExperienceYearsInCurrentRole,1200.0,NaN,NaN,NaN,4.291667,3.613744,0.0,2.0,3.0,7.0,18.0
YearsSinceLastPromotion,1200.0,NaN,NaN,NaN,2.194167,3.22156,0.0,0.0,1.0,3.0,15.0
YearsWithCurrManager,1200.0,NaN,NaN,NaN,4.105,3.541576,0.0,2.0,3.0,7.0,17.0
Attrition,1200,2,No,1022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PerformanceRating,1200.0,NaN,NaN,NaN,2.948333,0.518866,2.0,3.0,3.0,3.0,4.0

### Insight

The intial overview provides the overall size of the employee dataset and gives a first understanding of the variables availabe for analysis. The statistical summary also helps identify numerical ranges, categorical values, and potential unusual values that require futher investigation.

### 5. DATA STRUCTURE AND DATA TYPES

Understanding the structure and data types of each column is necessary before performing preprocessing. Numerical variables can be analyzed statistically and used directly by many machine elarning algorithms after appropriate preprocessing, while categorical variables may require encoding.

This step also helps identify columns that have been incorrectly imported, such as numerical values stored as strings.

### 5.1 Display Column Names (Column)

In [10]:
# Display columns names

print("Column names:\n")

for index, column in enumerate(df_processed.columns, start=1):
    print(f"{index}. {column}\n")

Column names:

1. EmpNumber

2. Age

3. Gender

4. EducationBackground

5. MaritalStatus

6. EmpDepartment

7. EmpJobRole

8. BusinessTravelFrequency

9. DistanceFromHome

10. EmpEducationLevel

11. EmpEnvironmentSatisfaction

12. EmpHourlyRate

13. EmpJobInvolvement

14. EmpJobLevel

15. EmpJobSatisfaction

16. NumCompaniesWorked

17. OverTime

18. EmpLastSalaryHikePercent

19. EmpRelationshipSatisfaction

20. TotalWorkExperienceInYears

21. TrainingTimesLastYear

22. EmpWorkLifeBalance

23. ExperienceYearsAtThisCompany

24. ExperienceYearsInCurrentRole

25. YearsSinceLastPromotion

26. YearsWithCurrManager

27. Attrition

28. PerformanceRating

### 5.2 Display Data Types (dtypes)

In [11]:
# Display data types

print("Data types of all columns:\n")

print(df_processed.dtypes)

Data types of all columns:

EmpNumber                       object
Age                              int64
Gender                          object
EducationBackground             object
MaritalStatus                   object
EmpDepartment                   object
EmpJobRole                      object
BusinessTravelFrequency         object
DistanceFromHome                 int64
EmpEducationLevel                int64
EmpEnvironmentSatisfaction       int64
EmpHourlyRate                    int64
EmpJobInvolvement                int64
EmpJobLevel                      int64
EmpJobSatisfaction               int64
NumCompaniesWorked               int64
OverTime                        object
EmpLastSalaryHikePercent         int64
EmpRelationshipSatisfaction      int64
TotalWorkExperienceInYears       int64
TrainingTimesLastYear            int64
EmpWorkLifeBalance               int64
ExperienceYearsAtThisCompany     int64
ExperienceYearsInCurrentRole     int64
YearsSinceLastPromotion          int64
YearsWithCurrManager             int64
Attrition                       object
PerformanceRating                int64
dtype: object

### 5.3 Count Numerical and Categorical Columns (numerical , categorical)

In [12]:
# Count numerical columns

numerical_columns = df_processed.select_dtypes(
    include = ["int64", "float64"]
).columns.tolist()

# Count categorical columns

categorical_columns = df_processed.select_dtypes(
    include = ["object", "category", "bool"]
).columns.tolist()

print(f"Number of numerical columns: {len(numerical_columns)}\n")
print(f"Number of categorical columns: {len(categorical_columns)}\n")

print(f"Numerical columns: {numerical_columns}\n")
print(f"Categorical columns: {categorical_columns}\n")

Number of numerical columns: 19

Number of categorical columns: 9

Numerical columns: ['Age', 'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction', 'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel', 'EmpJobSatisfaction', 'NumCompaniesWorked', 'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction', 'TotalWorkExperienceInYears', 'TrainingTimesLastYear', 'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany', 'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'PerformanceRating']

Categorical columns: ['EmpNumber', 'Gender', 'EducationBackground', 'MaritalStatus', 'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency', 'OverTime', 'Attrition']

### 5.4 Dispaly Details information about the dataset (info)

In [13]:
# Display details information about the dataset

print("Dataset information:\n")

print(df_processed.info())

Dataset information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmpNumber                     1200 non-null   object
 1   Age                           1200 non-null   int64
 2   Gender                        1200 non-null   object
 3   EducationBackground           1200 non-null   object
 4   MaritalStatus                 1200 non-null   object
 5   EmpDepartment                 1200 non-null   object
 6   EmpJobRole                    1200 non-null   object
 7   BusinessTravelFrequency       1200 non-null   object
 8   DistanceFromHome              1200 non-null   int64
 9   EmpEducationLevel             1200 non-null   int64
 10  EmpEnvironmentSatisfaction    1200 non-null   int64
 11  EmpHourlyRate                 1200 non-null   int64
 12  EmpJobInvolvement             1200 non-null   int64
 13  EmpJobLevel                   1200 non-null   int64
 14  EmpJobSatisfaction            1200 non-null   int64
 15  NumCompaniesWorked            1200 non-null   int64
 16  OverTime                      1200 non-null   object
 17  EmpLastSalaryHikePercent      1200 non-null   int64
 18  EmpRelationshipSatisfaction   1200 non-null   int64
 19  TotalWorkExperienceInYears    1200 non-null   int64
 20  TrainingTimesLastYear         1200 non-null   int64
 21  EmpWorkLifeBalance            1200 non-null   int64
 22  ExperienceYearsAtThisCompany  1200 non-null   int64
 23  ExperienceYearsInCurrentRole  1200 non-null   int64
 24  YearsSinceLastPromotion       1200 non-null   int64
 25  YearsWithCurrManager          1200 non-null   int64
 26  Attrition                     1200 non-null   object
 27  PerformanceRating             1200 non-null   int64
dtypes: int64(19), object(9)
memory usage: 262.6+ KB
None

### Insight

The data-type analysis identifies numerical and categorical variables and confirms whether the dataset has been imported correctly. Any incorrectly types variables should be corrected before proceeding to modeling.

### 6. DATA QUALITY ASSESSMENT

Data quality assessment is performed to identify potential problems in the dataset before analysis. Important checks including the number of records, number of column, missing values, duplicate records, unquie values, and data types.

Thesse checks helpd determine whether the dataste is complete, consistent, and suitable for futher preprocessing.

### 6.1 Create a Data Quality Summary

In [14]:
# Create a data quality summary

quality_summary = pd.DataFrame({
    "Columns": df_processed.columns,
    "Data_Type": df_processed.dtypes.astype(str).values,
    "Non_Null_Count": df_processed.notnull().sum().values,
    "Missing_Count": df_processed.isnull().sum().values,
    "Unique_Count": df_processed.nunique().values
})

quality_summary["Missing_Percentage"]=(
    quality_summary["Missing_Count"]
    / len(df_processed)
)*100

display(quality_summary)

print(f"Total records assessed: {len(df_processed)}\n")
print(f"Total columns assessed: {df_processed.shape[1]}\n")
print(f"Total missing values in dataset:"
      f"{df_processed.isnull().sum().sum()}\n")
print(f"Total duplicate records:"
      f"{df_processed.duplicated().sum()}")

,Columns,Data_Type,Non_Null_Count,Missing_Count,Unique_Count,Missing_Percentage
0,EmpNumber,object,1200,0,1200,0.0
1,Age,int64,1200,0,43,0.0
2,Gender,object,1200,0,2,0.0
3,EducationBackground,object,1200,0,6,0.0
4,MaritalStatus,object,1200,0,3,0.0
5,EmpDepartment,object,1200,0,6,0.0
6,EmpJobRole,object,1200,0,19,0.0
7,BusinessTravelFrequency,object,1200,0,3,0.0
8,DistanceFromHome,int64,1200,0,29,0.0
9,EmpEducationLevel,int64,1200,0,5,0.0
10,EmpEnvironmentSatisfaction,int64,1200,0,4,0.0
11,EmpHourlyRate,int64,1200,0,71,0.0
12,EmpJobInvolvement,int64,1200,0,4,0.0
13,EmpJobLevel,int64,1200,0,5,0.0
14,EmpJobSatisfaction,int64,1200,0,4,0.0
15,NumCompaniesWorked,int64,1200,0,10,0.0
16,OverTime,object,1200,0,2,0.0
17,EmpLastSalaryHikePercent,int64,1200,0,15,0.0
18,EmpRelationshipSatisfaction,int64,1200,0,4,0.0
19,TotalWorkExperienceInYears,int64,1200,0,40,0.0
20,TrainingTimesLastYear,int64,1200,0,7,0.0
21,EmpWorkLifeBalance,int64,1200,0,4,0.0
22,ExperienceYearsAtThisCompany,int64,1200,0,37,0.0
23,ExperienceYearsInCurrentRole,int64,1200,0,19,0.0
24,YearsSinceLastPromotion,int64,1200,0,16,0.0
25,YearsWithCurrManager,int64,1200,0,18,0.0
26,Attrition,object,1200,0,2,0.0
27,PerformanceRating,int64,1200,0,3,0.0

Total records assessed: 1200

Total columns assessed: 28

Total missing values in dataset:0

Total duplicate records:0

### Insight

The data quality assessment provides a cloumn-level view of completeness and uniqueness. Columns with missing values, unexpected data types, or unusually low/high numbers of unique values should be investigated before the dataset is used for modeling.

### 7. MISSING VALUE ANALYSIS

Missing values can affect statistical analysis and machine learning algorithms. Therfore, every column is checked for missing observations. The number and percentage of missing values are calculated to determine whether additional treatment is required.

The treatment strategy depends on the amount of missing data and the meaning of the corresponding variable. Missing values should not automatically be removed without understanding their impact.

### 7.1 Calculate Missing Values

In [15]:
# Calculate missing values

missing_summary = pd.DataFrame({
    "Missing_Count": df_processed.isnull().sum(),
    "Missing_Precentage": (
        df_processed.isnull().sum()
        / len(df_processed)
    )*100
})

missing_summary = missing_summary.sort_values(
    by = "Missing_Count",
    ascending = False
)

### 7.2 Identify Columns Containing Missing Values

In [16]:
# Identify columns containing missing values

missing_columns = missing_summary[
    missing_summary["Missing_Count"]>0
]

print(f"Number of columns containing missing values: {len(missing_columns)}")

if len(missing_columns)>0:

    print("Columns with missing values:\n")

    for column in missing_columns.index:
        count = missing_summary.loc[column, "Missing_Count"]
        percentage = missing_summary.loc[column, "Missing_Percentage"]

        print(
        f"{column}:"
        f"{int(count)} missing values"
        f"({percentage:.2f}%)"
        )
else:
        print("No missing values were found in the dataset.")

Number of columns containing missing values: 0
No missing values were found in the dataset.

### Insight

The missing-value analysis determines whether the dataset requires imputation or record removal. If no missing values are present, no-missing-value treatment is necessary. If missing values exist, the approprite treatment should be selected based on the variable type and business meaning.

### 8. DUPLICATE RECORDS ANALYSIS

Duplicate records can create bias by causing the same employee observation to appear more than once. Therefore, the dataset is checked for completely duplicated rows.

If duplicate records are found, they can normally be removed when they represent accidental duplication rather than legitimate repeated observation.

### 8.1 Count Duplicate Records

In [17]:
# Count duplicate records

duplicate_count = df_processed.duplicated().sum()

print(f"Number of duplicate records: {duplicate_count}")

Number of duplicate records: 0

### 8.2 Display Duplicate Records If Present

In [18]:
# Display duplicate records if present

if duplicate_count > 0:

    duplicate_rows = df.processed[
        df_processed.duplicated(keep = False)
    ]

    print(f"Displaying {len(duplicate_rows)} duplicate-related rows:")
    display(duplicate_rows)
else:
    print("No duplicate records found.")

No duplicate records found.

### 8.3 Remove Duplicate Records

In [19]:
# Remove duplicate records

before_duplicates = len(df_processed)
df_processed = df_processed.drop_duplicates()

after_duplicates = len(df_processed)

removed_duplicates = (
    before_duplicates - after_duplicates
)

print(f"Records before duplicate removal: {before_duplicates}\n")
print(f"Records after duplicate removal: {after_duplicates}\n")
print(f"Duplicate records removed: {removed_duplicates}")

Records before duplicate removal: 1200

Records after duplicate removal: 1200

Duplicate records removed: 0

### Insight

Duplicate records have been checked and removed when present. Removing accidental duplicates prevents repeadted observations from dispropoortiontely influencing descriptive statistics and machine learning models.

### 9. TARGET VARIABLE VALIDATION

The target variable is te variable that the machine elarning model will attempt to project. For the INX Future Inc Employee Performance project, the expected target variable is `PerformanceRating`.

The target variable must be checked for existence, data type, missing values, unique values, and class distribution. This validation ensures that the target is correctly identified before feature engineering and model training.

### 9.1 Define Target Variable

In [20]:
target_column = "PerformanceRating"

print(f"Target variable selected: {target_column}")

if target_column in df_processed.columns:
    print("Target variable exists in the dataset.")
else:
    print(
        f"WARNING: Target variable '{target_column}'"
        f"was not fount in the dataset."
    )

Target variable selected: PerformanceRating
Target variable exists in the dataset.

### 9.2 Validate Target Variable

In [21]:
# Validate target variable

if target_column in df_processed.columns:
    print(f"Target data type: {df_processed[target_column].dtype}\n")
    
    print(
    f"Missing target values: "
    f"{df_processed[target_column].isnull().sum()}\n"
    )

    print(
    f"Number of unique target values: "
    f"{df_processed[target_column].nunique()}\n"
    )

    print(
    f"Unique target values: "
    f"{sorted(df_processed[target_column].dropna().unique())}"
    )

Target data type: int64

Missing target values: 0

Number of unique target values: 3

Unique target values: [np.int64(2), np.int64(3), np.int64(4)]

### 9.3 Target Distribution - Display Target Variable Distribution

In [22]:
# Display target variable distribution

if target_column in df_processed.columns:

    target_distribution = (
        df_processed[target_column]
        .value_counts()
        .sort_index()
    )

    display(target_distribution.to_frame("Count"))

                   Count
PerformanceRating
2                    194
3                    874
4                    132

### 9.4 Calculate Target Percentage Distribution

In [23]:
# Calculate target percentage distribution

if target_column in df_processed.columns:
    target_percentage = (
        df_processed[target_column]
        .value_counts(normalize = True)
        .sort_index()
        * 100
    )

    for value, percentage in target_percentage.items():

        print(
            f"PerformanceRating = {value}:"
            f"{percentage:.2f}%"
        )

PerformanceRating = 2:16.17%
PerformanceRating = 3:72.83%
PerformanceRating = 4:11.00%

### Insight

The target variable is validate for availability, completeness, and class distribution. Understanding the target distribution is important because a highly imbalanced target may require special consideration during model evaluation and training.

### 10. DATA CLEANING

Data cleaning involves correcting inconsistencies and preparing the dataset for analysis. The clearning process includes standardizing column names, checking for invalid or unexpected values.

### 10.1 Clean Column Names - Standardize Column Names

In [24]:
# Standardize column names

original_columns = df_processed.columns.tolist()

df_processed.columns = (
    df_processed.columns
    .str.strip()
)

print("Column names after removing leading/trailing spaces:\n")

for column in df_processed.columns:
    print(f"- {column}")

Column names after removing leading/trailing spaces:

- EmpNumber
- Age
- Gender
- EducationBackground
- MaritalStatus
- EmpDepartment
- EmpJobRole
- BusinessTravelFrequency
- DistanceFromHome
- EmpEducationLevel
- EmpEnvironmentSatisfaction
- EmpHourlyRate
- EmpJobInvolvement
- EmpJobLevel
- EmpJobSatisfaction
- NumCompaniesWorked
- OverTime
- EmpLastSalaryHikePercent
- EmpRelationshipSatisfaction
- TotalWorkExperienceInYears
- TrainingTimesLastYear
- EmpWorkLifeBalance
- ExperienceYearsAtThisCompany
- ExperienceYearsInCurrentRole
- YearsSinceLastPromotion
- YearsWithCurrManager
- Attrition
- PerformanceRating

### 10.2 Check Numeric Columns - Check Numerical Columns For Negative Values

In [25]:
# Check numerical columns for negative values

numeric_columns = df_processed.select_dtypes(
    include = np.number
).columns

for column in numeric_columns:
    negative_count = (
        df_processed[column] < 0
    ).sum()

    print(
    f"{column}:"
    f"{negative_count} negative values"
    )

Age:0 negative values
DistanceFromHome:0 negative values
EmpEducationLevel:0 negative values
EmpEnvironmentSatisfaction:0 negative values
EmpHourlyRate:0 negative values
EmpJobInvolvement:0 negative values
EmpJobLevel:0 negative values
EmpJobSatisfaction:0 negative values
NumCompaniesWorked:0 negative values
EmpLastSalaryHikePercent:0 negative values
EmpRelationshipSatisfaction:0 negative values
TotalWorkExperienceInYears:0 negative values
TrainingTimesLastYear:0 negative values
EmpWorkLifeBalance:0 negative values
ExperienceYearsAtThisCompany:0 negative values
ExperienceYearsInCurrentRole:0 negative values
YearsSinceLastPromotion:0 negative values
YearsWithCurrManager:0 negative values
PerformanceRating:0 negative values

### Insight

The basic cleaning stage standaridizes column names and verifies whether missing or potentially invalid numerical remain. No transformation should be applied merely to make the data look cleaner; every modification should have a logical or business justification.

### 11. FEATURE IDENTIFICATION

Feature identification separates the dataset into predictor variables and target variable. Predictor variables contain information that may help explain or predict employee performance, while the target variable represents the employee performance outcome.

### 11.1 Identify Target and Feature Columns

In [26]:
# Identify target and feature columns

if target_column in df_processed.columns:
    feature_columns = [
        column
        for column in df_processed.columns
        if columns != target_column
    ]

    print(f"Target column: {target_column}")
    print(f"Number of feature columns: {len(feature_columns)}")

    print("\nFeature columns:\n")

    for index, column in enumerate(feature_columns, start=1):
        print(f"{index}. {column}")
else:
        feature_columns = []

        print(
        f"Cannot identify features because"
        f"target column '{target_column}' is missing."
        )

Target column: PerformanceRating
Number of feature columns: 28

Feature columns:

1. EmpNumber
2. Age
3. Gender
4. EducationBackground
5. MaritalStatus
6. EmpDepartment
7. EmpJobRole
8. BusinessTravelFrequency
9. DistanceFromHome
10. EmpEducationLevel
11. EmpEnvironmentSatisfaction
12. EmpHourlyRate
13. EmpJobInvolvement
14. EmpJobLevel
15. EmpJobSatisfaction
16. NumCompaniesWorked
17. OverTime
18. EmpLastSalaryHikePercent
19. EmpRelationshipSatisfaction
20. TotalWorkExperienceInYears
21. TrainingTimesLastYear
22. EmpWorkLifeBalance
23. ExperienceYearsAtThisCompany
24. ExperienceYearsInCurrentRole
25. YearsSinceLastPromotion
26. YearsWithCurrManager
27. Attrition
28. PerformanceRating

### Insight

The target variable has been identified separately from the predictor variables. The remaining columns represent the features that may be used to predict employee perfomance.

### 12. PROCESSED DATASET CREATION

After completing the data-quality checks and cleaning operations, the processed dataset is saved separately from the raw dataset. This preserves the original data and creates a reproducible workflow.

The processed dataset will be used in subsequent notebook for EDA, visulaization, feature engineering, and machine learning model development.

### 12.1 Create Processed Folder - Create Processed-Data Directory If It Does Not Exist

In [27]:
# Create processed-data directory if it does not exist

os.makedirs(
    processed_path,
    exist_ok = True
)

print(f"Processed data directory is ready: {processed_path}")

Processed data directory is ready: E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed

### 12.2 Final Dataset Check - Final Dataset Shape

In [28]:
# Final Dataset Shape

print(f"Final processed dataset rows: {df_processed.shape[0]}")
print(f"Final processed dataset columns: {df_processed.shape[1]}")

print("\nFinal columns:\n")

for index, column in enumerate(
    df_processed.columns,
    start = 1
):
    print(f"{index}. {column}")

Final processed dataset rows: 1200
Final processed dataset columns: 28

Final columns:

1. EmpNumber
2. Age
3. Gender
4. EducationBackground
5. MaritalStatus
6. EmpDepartment
7. EmpJobRole
8. BusinessTravelFrequency
9. DistanceFromHome
10. EmpEducationLevel
11. EmpEnvironmentSatisfaction
12. EmpHourlyRate
13. EmpJobInvolvement
14. EmpJobLevel
15. EmpJobSatisfaction
16. NumCompaniesWorked
17. OverTime
18. EmpLastSalaryHikePercent
19. EmpRelationshipSatisfaction
20. TotalWorkExperienceInYears
21. TrainingTimesLastYear
22. EmpWorkLifeBalance
23. ExperienceYearsAtThisCompany
24. ExperienceYearsInCurrentRole
25. YearsSinceLastPromotion
26. YearsWithCurrManager
27. Attrition
28. PerformanceRating

### 12.3 Save Dataset - Save Processed Dataset

In [29]:
processed_file = os.path.join(
    processed_path,
    "employee_performance_processed.csv"
)

df_processed.to_csv(
    processed_file,
    index = False
)

print(f"Processed dataset saved successfully.")
print(f"File location: {processed_file}")
print(f"Save records: {df_processed.shape[0]}")
print(f"Saved columns: {df_processed.shape[1]}")

Processed dataset saved successfully.
File location: E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed\employee_performance_processed.csv
Save records: 1200
Saved columns: 28

### 12.4 Verify Saved File - Verify That The Processed File Exists

In [30]:
# Verify that the processed file exists

if os.path.exists(processed_file):
    file_size_kb = (
        os.path.getsize(processed_file)
        / 1024
    )

    print(f"Processed file exists: YES")
    print(f"File size: {file_size_kb:.2f} KB")

else:
    print("Processed file was not created.")

Processed file exists: YES
File size: 149.13 KB

### Insight

The cleaned employee performance dataset has been saved in the processed-data directory. The raw dataset remains unchanged, while the processed version can now be used safely for subsequent analysis and model development.

### 13. DATA PROCESSING SUMMARY

The data processing stage involved loading the raw employee performance dataset, examining its structure, assessing data quality, checking missing values and duplicate records, validating the target variable, identifying useful features, removing identifier or constant columns where appropriate, and saving the cleaned dataset.

The purpose of this process is to establish a reliable and reproducible foundation for exploratory data analysis and machine learning. All preprocessing decisions should be documented so that the project can be understood and reproduced by other users.

### 13.1 Final Summary - Generate Final Processing Summary

In [31]:
# Generate final processing summary

initial_rows = df.shape[0]
initial_columns = df.shape[1]

final_rows = df_processed.shape[0]
final_columns = df_processed.shape[1]

rows_removed = initial_rows - final_rows
columns_removed = initial_columns - final_columns

remaining_missing = (
    df_processed.isnull().sum().sum()
)

remaining_duplicates = (
    df_processed.duplicated().sum()
)

print("=" * 60)
print("INX FUTURE INC EMPLOYEE PERFORMANCE")
print("DATA PROCESSING SUMMARY")
print("=" * 60)

print(f"Initial number of rows       : {initial_rows}")
print(f"Initial number of columns    : {initial_columns}")

print(f"Final number of rows         : {final_rows}")
print(f"Final number of columns      : {final_columns}")

print(f"Rows removed                 : {rows_removed}")
print(f"Columns removed              : {columns_removed}")

print(f"Remaining missing values     : {remaining_missing}")
print(f"Remaining duplicate records  : {remaining_duplicates}")

print(f"Target variable              : {target_column}")

print(f"Processed dataset saved at   : {processed_file}")

print("=" * 60)
print("Data processing completed successfully.")
print("=" * 60)

============================================================
INX FUTURE INC EMPLOYEE PERFORMANCE
DATA PROCESSING SUMMARY
============================================================
Initial number of rows       : 1200
Initial number of columns    : 28
Final number of rows         : 1200
Final number of columns      : 28
Rows removed                 : 0
Columns removed              : 0
Remaining missing values     : 0
Remaining duplicate records  : 0
Target variable              : PerformanceRating
Processed dataset saved at   : E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed\employee_performance_processed.csv
============================================================
Data processing completed successfully.
============================================================

### Insight

The final summary confirms the outcome of the preprocessing stage. The processed dataset is now organized, checked for missing and duplicate observations, and separated from the original raw dataset. This processed file provides the input for the next stage of the project.

## 14. CONCLUSION

The data processing stage successfully prepared the INX Future Inc Employee Performance dataset for further analysis. The dataset was loaded from the raw-data directory and systematically examined for its structure, data types, missing values, duplicate records, target-variable validity, and potentially irrelevant columns.

After the required cleaning and validation steps, the processed dataset was stored separately in the `data/processed` directory. Maintaining separate raw and processed datasets improves reproducibility and protects the original source data.

The next stage of the project will use the processed dataset to perform detailed exploratory data analysis, identify relationships between employee attributes and performance, analyze important patterns, and generate visualizations that support the subsequent machine learning stage.

### 14.1 Final Data Processing Summary

In [32]:
# Final Data Processing Summary

print("=" * 70)
print("INX FUTURE INC EMPLOYEE PERFORMANCE")
print("DATA PROCESSING COMPLETED SUCCESSFULLY")
print("=" * 70)

print(f"Initial number of rows       : {initial_rows}")
print(f"Initial number of columns    : {initial_columns}")

print(f"Final number of rows         : {final_rows}")
print(f"Final number of columns      : {final_columns}")

print(f"Rows removed                 : {rows_removed}")
print(f"Columns removed              : {columns_removed}")

print(f"Remaining missing values     : {remaining_missing}")
print(f"Remaining duplicate records  : {remaining_duplicates}")

print(f"Target variable              : {target_column}")
print(f"Processed dataset saved at   : {processed_file}")

print("\nNext Step:")


print("-" * 70)
print("NEXT STAGE : EXPLORATORY DATA ANALYSIS (EDA)")
print("-" * 70)

======================================================================
INX FUTURE INC EMPLOYEE PERFORMANCE
DATA PROCESSING COMPLETED SUCCESSFULLY
======================================================================
Initial number of rows       : 1200
Initial number of columns    : 28
Final number of rows         : 1200
Final number of columns      : 28
Rows removed                 : 0
Columns removed              : 0
Remaining missing values     : 0
Remaining duplicate records  : 0
Target variable              : PerformanceRating
Processed dataset saved at   : E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed\employee_performance_processed.csv

Next Step:
----------------------------------------------------------------------
NEXT STAGE : EXPLORATORY DATA ANALYSIS (EDA)
----------------------------------------------------------------------