# INX FUTURE INC EMPLOYEE PERFORMANCE - PREDICTION

## 1. INTRODUCTION
## 2. PREDICTION OBJECTIVE
## 3. LOADING REQUIRED LIBRARIES
## 4. LOADING THE TRAINED MODEL
## 5. LOADING EMPLOYEE DATA
## 6. PREPARING INPUT DATA
## 7. GENERATING EMPLOYEE PERFORMANCE PREDICTIONS
## 8. PREDICTION PROBABILITIES
## 9. EMPLOYEE-WISE PREDICTION RESULTS
## 10. IDENTIFICATION OF POTENTIAL LOW PERFORMERS
## 11. PREDICTION INTERPRETATION
## 12. BUSINESS INSIGHTS
## 13. RECOMMENDATIONS
## 14. ETHICAL CONSIDERATIONS
## 15. MODEL LIMITATION
## 16. CONCLUSION

# INX Future Inc Employee Performance - Prediction

## 1. INTRODUCTION

This notebook uses the trained machine learning model developed in the model training stage to predict employee performance ratings for employee records. The saved model contains both the preprocessing steps and the classification algorithm, allowing new employee data to be passed through the same transformation process used during training.

The prediction workflow includes loading the trained model, employee data, preparing the input data, generating predictions, calculating prediction probabilities where supported, identifying employees who may require additional attention, and interpreting the results from a business perpective.

### 1.1 Import Required Libraries For Prediction

In [1]:
# Import required libraries for prediction

import os 
import warnings
import joblib
import numpy as np
import pandas as pd
warnings.filterwarnings("ignore")

print(f"Required libraries imported successfully.")

Required libraries imported successfully.

### Insight

The required Python libraries have been imported successfully. joblib will be used to load the trained machine learning model, while pandas and numpy will be used to prepare and analyze employee data.

## 2. PREDICTION OBJECTIVE

The objective of this notebook is to use the trained machine learning model to predict the PerformanceRating of employees based on their available employee-related attributes.

The prediction system is intended to demonstrate how a trained machine learning model can be applied to employee data after the model development stage.

### 2.1 Define Project and Prediction Settings

In [2]:
# Define project and prediction settings

project_name = "INX_Future_Inc_Employee_Performance"
target_column = "PerformanceRating"

print(f"Project Name: {project_name}")
print(f"Target Column: {target_column}")
print(f"Prediction objective: Predict employee performance rating.")

Project Name: INX_Future_Inc_Employee_Performance
Target Column: PerformanceRating
Prediction objective: Predict employee performance rating.

### Insight

The target variable for prediction is PerformanceRating. The trained model will use employee attributes as input and return the predicted performance category.

## 3. LOADING REQUIRED LIBRARIES

The prediction notebook requires libraries for file handling, data manipulation, numerical operations, and loading the trained machine elarning model.

### 3.1 Display The Main Libraries Used In This Notebook

In [3]:
# Display the main libraries used in this notebook

required_libraries = [
    "os",
    "joblib",
    "numby",
    "pandas"
]

print(f"Number of required libraries: {len(required_libraries)}")
print(f"Libraries: {','.join(required_libraries)}")

Number of required libraries: 4
Libraries: os,joblib,numby,pandas

### Insight

The prediction environment contains the libraries required to load the trained model and process employee records.

## 4. LOADING THE TRAINED MODEL

The trained model was saved during the train_model.ipynb stage as a .joblib file.

The saved object contains the complete machine learning pipeline, including preprocessing and the final classification model. Using the complete pipeline helps ensure that employee data is transformed consistently with data used during training.

### 4.1 Define The Location of The Trained Model

In [7]:
# Define the location of the trained model

model_path = os.getcwd()

model_file = os.path.join(
    model_path,
    "employee_performance_model.joblib"
)

print(f"Model directory: {model_path}")
print(f"Model file: {model_file}")

if os.path.exists(model_file):
    print("Trained model file found successfully.")
else:
    print("ERROR: Trained model file was not found.")

Model directory: E:\IABAC\INX_Future_Inc_Employee_Performance\src\models
Model file: E:\IABAC\INX_Future_Inc_Employee_Performance\src\models\employee_performance_model.joblib
Trained model file found successfully.

### 4.2 Load The Trained Machine Learning Pipeline

In [8]:
# Load the trained machine learning pipeline

if os.path.exists(model_file):
    trained_model = joblib.load(model_file)

    print(f"Trained model loaded successfully.")
    print(f"Model type: {type(trained_model).__name__}")

else:
    raise FIleNotFoundError(
        f"Trained model not found at: {model_file}"
    )

Trained model loaded successfully.
Model type: Pipeline

### Insight

The trained model has been loaded successfully. Because the saved object is the complete pipeline, the same preprocessing logic used during model training can be automatically applied during prediction.

## 5. LOADING EMPLOYEE DATA

The prediction process requires employee records containing the same input features that were available during model training.

The processed employee dataset is loaded from the data/processed directory.

### 5.1 Define The Processed Employee Dataset Path

In [12]:
# Define the processed employee datasetpath

project_root = os.path.abspath(
    os.path.join(os.getcwd(), "..", "..")
)


processed_path = os.path.join(
    project_root,
    "data",
    "processed"
)


employee_file = os.path.join(
    processed_path,
    "employee_performance_processed.csv"
)

print(f"Project root: {project_root}")
print(f"Processed data directory: {processed_path}")
print(f"Employee data file: {employee_file}")

if os.path.exists(employee_file):
    print("Employee dataset found successfully.")
else:
    print("ERROR: Employee dataset was not found.")

Project root: E:\IABAC\INX_Future_Inc_Employee_Performance
Processed data directory: E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed
Employee data file: E:\IABAC\INX_Future_Inc_Employee_Performance\data\processed\employee_performance_processed.csv
Employee dataset found successfully.

### 5.2 Load Employee Data

In [13]:
# Load employee data

employee_df = pd.read_csv(employee_file)

print(f"Employee data loaded successfully.")
print(f"Number of rows: {employee_df.shape[0]}")
print(f"Number of columns: {employee_df.shape[1]}")

Employee data loaded successfully.
Number of rows: 1200
Number of columns: 28

### 5.3 Display The First Five Employee Recordsm

In [14]:
# Display the first five employee recordsm

print(f"First five employee records:")

display(employee_df.head())

First five employee records:

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

### Insight

The employee dataset has been successfully loaded. The number of rows and columns provides an initial understanding of the data available for prediction.

## 6. PREPARING INPUT DATA

The target column must not be supplied to the model when generating predictions because the purpose of prediction is to estimate the target value.
Therefore, if the dataset contains an existing PerformanceRating column, it is removed before prediction.
The model will receive only the feature columns used during model development.

### 6.1 Create a Copy of the Employee Dataset

In [15]:
# Create a copy of the employee dataset

prediction_data = employee_df.copy()

print(f"Prediction dataset created.")
print(f"Rows available for prediction: {prediction_data.shape[0]}")
print(f"Columns available before target removal: {prediction_data.shape[1]}")

Prediction dataset created.
Rows available for prediction: 1200
Columns available before target removal: 28

### 6.2 Remove the Target Column if it Exists

In [16]:
# Remove the target column if it exists

if target_column in prediction_data.columns:

    prediction_input = prediction_data.drop(
        columns=[target_column]
    )

    print(f"Target column '{target_column}' removed from prediction input.")
    print(f"Number of input features: {prediction_input.shape[1]}")

else:

    prediction_input = prediction_data.copy()

    print(f"Target column '{target_column}' was not present.")
    print(f"All available columns will be used as input features.")

Target column 'PerformanceRating' removed from prediction input.
Number of input features: 27

### 6.3 Check the Input Feature Columns

In [17]:
# Check the input feature columns

print(f"Prediction input columns:")

for index, column in enumerate(
    prediction_input.columns,
    start=1
):

    print(f"{index}. {column}")

Prediction input columns:
1. EmpNumber
2. Age
3. Gender
4. EducationBackground
5. MaritalStatus
6. EmpDepartment
7. EmpJobRole
8. BusinessTravelFrequency
9. DistanceFromHome
10. EmpEducationLevel
11. EmpEnvironmentSatisfaction
12. EmpHourlyRate
13. EmpJobInvolvement
14. EmpJobLevel
15. EmpJobSatisfaction
16. NumCompaniesWorked
17. OverTime
18. EmpLastSalaryHikePercent
19. EmpRelationshipSatisfaction
20. TotalWorkExperienceInYears
21. TrainingTimesLastYear
22. EmpWorkLifeBalance
23. ExperienceYearsAtThisCompany
24. ExperienceYearsInCurrentRole
25. YearsSinceLastPromotion
26. YearsWithCurrManager
27. Attrition

### Insight

The target variable has been separated from the prediction input. Only independent employee attributes are supplied to the trained model.

## 7. GENERATING EMPLOYEE PERFORMANCE PREDICTIONS

The trained pipeline is now used to generate performance predictions.

The model applies the required preprocessing automatically and then generates the predicted PerformanceRating for each employee.

### 7.1 Generate Employee Performance Predictions

In [19]:
# Generate employee performance predictions

predicted_performance = trained_model.predict(
    prediction_input
)

print(f"Predictions generated successfully.")
print(f"Number of predictions: {len(predicted_performance)}")

Predictions generated successfully.
Number of predictions: 1200

### 7.2 Add Predictions to a Result DataFrame

In [20]:
# Add predictions to a results dataframe

prediction_results = employee_df.copy()

prediction_results["PredictedPerformanceRating"] = predicted_performance

print(f"Prediction results created successfully.")
print(f"Number of employee records: {prediction_results.shape[0]}")

Prediction results created successfully.
Number of employee records: 1200

### 7.3 Display Sample Predictions

In [21]:
# Display sample predictions

print(f"Sample employee performance predictions:")

display(
    prediction_results[
        ["PredictedPerformanceRating"]
    ].head(10)
)

Sample employee performance predictions:

   PredictedPerformanceRating
0                           3
1                           3
2                           4
3                           3
4                           3
5                           4
6                           3
7                           3
8                           3
9                           3

### Insight

The trained model has generated a performance rating prediction for every employee record. These predictions can now be analyzed employee by employee.

## 8. PREDICTION PROBABILITIES

Prediction probabilities represent the model's estimated probability for each possible performance class.
Not every machine learning classifier provides probability estimates. Therefore, this section checks whether the trained model supports predict_proba() before calculating probabilities.

### 8.1 Check Whether the Trained Model Supports Prediction Probabilites

In [22]:
# Check whether the trained model supports prediction probabilities

if hasattr(trained_model, "predict_proba"):

    prediction_probabilities = trained_model.predict_proba(
        prediction_input
    )

    print(f"Prediction probabilities generated successfully.")
    print(f"Probability matrix shape: {prediction_probabilities.shape}")

else:

    prediction_probabilities = None

    print(f"The selected trained model does not provide prediction probabilities.")

Prediction probabilities generated successfully.
Probability matrix shape: (1200, 3)

### 8.2 Extract Model Classes When Probability Estimates are Available

In [23]:
# Extract model classes when probability estimates are available

if prediction_probabilities is not None:

    model_classes = trained_model.classes_

    print(f"Performance classes available in the model:")

    for index, class_value in enumerate(model_classes):

        print(f"Class {index + 1}: {class_value}")

else:

    model_classes = None

    print(f"No probability classes available.")

Performance classes available in the model:
Class 1: 2
Class 2: 3
Class 3: 4

### 8.3 Add Probabilites Columns to the Prediction Results

In [24]:
# Add probability columns to the prediction results

if prediction_probabilities is not None:

    for index, class_value in enumerate(model_classes):

        probability_column = (
            f"Probability_Performance_{class_value}"
        )

        prediction_results[probability_column] = (
            prediction_probabilities[:, index]
        )

        print(
            f"Added probability column: "
            f"{probability_column}"
        )

else:

    print(f"No probability columns were added.")

Added probability column: Probability_Performance_2
Added probability column: Probability_Performance_3
Added probability column: Probability_Performance_4

### Insight

Probability values provide additional information beyond the predicted class. For example, a prediction with a probability close to 0.95 indicates stronger model confidence than a prediction with a probability close to 0.55.
However, model probability should be interpreted as a model estimate rather than a guarantee of employee performance.

## 9. EMPLOYEE-WISE PREDICTION RESULTS

Employee-wise prediction results combine the available employee information with the model's predicted performance rating.
An employee identifier is used when available so that predictions can be traced back to individual records.

### 9.1 Identify a Suitable Employee Identifier

In [27]:
# Identify a suitable employee identifier

possible_id_columns = [
    "EmpNumber",
    "EmpID",
    "EmpId",
    "id"
]

employee_id_column = None

for column in possible_id_columns:

    if column in prediction_results.columns:

        employee_id_column = column
        break

if employee_id_column is not None:

    print(f"Employee identifier found: {employee_id_column}")

else:

    print(f"No standard employee identifier column was found.")

Employee identifier found: EmpNumber

### 9.2 Display Employee-Wise Prediction Results

In [30]:
# Display employee-wise prediction results

if employee_id_column is not None:

    employee_prediction_view = prediction_results[
        [
            employee_id_column,
            "PredictedPerformanceRating"
        ]
    ].copy()

else:

    employee_prediction_view = prediction_results[
        [
            "PredictedPerformanceRating"
        ]
    ].copy()

print(f"Employee-wise prediction results:")

display(
    employee_prediction_view.head(20)
)

Employee-wise prediction results:

   EmpNumber  PredictedPerformanceRating
0   E1001000                           3
1   E1001006                           3
2   E1001007                           4
3   E1001009                           3
4   E1001010                           3
5   E1001011                           4
6   E1001016                           3
7   E1001019                           3
8   E1001020                           3
9   E1001021                           3
10  E1001022                           3
11  E1001024                           3
12  E1001025                           4
13  E1001027                           3
14  E1001030                           3
15  E1001035                           3
16  E1001038                           3
17  E1001040                           3
18  E1001041                           4
19  E1001042                           3

### 9.3 Display Prediction Distribution

In [31]:
# Display prediction distribution

prediction_distribution = (
    prediction_results[
        "PredictedPerformanceRating"
    ]
    .value_counts()
    .sort_index()
)

print(f"Predicted performance rating distribution:")

for rating, count in prediction_distribution.items():

    print(
        f"Performance Rating {rating}: "
        f"{count} employees"
    )

Predicted performance rating distribution:
Performance Rating 2: 188 employees
Performance Rating 3: 888 employees
Performance Rating 4: 124 employees

### Insight

The employee-wise results show the predicted performance category for each employee. The prediction distribution also helps identify how the model is classifying the employee population across performance categories.

### 10. IDENTIFICATION OF POTENTIAL LOW PERFORMERS

One important business application of an employee performance prediction model is to identify employees whose predicted performance rating falls into a lower category.
This should not be interpreted as a final judgment about an employee. Instead, these records can be treated as cases for additional review, support, training, or development.

### 10.1 Identify The Lowest Predicted Performance Rating

In [32]:
# Identify the lowest predicted performance rating

unique_predictions = sorted(
    prediction_results[
        "PredictedPerformanceRating"
    ].dropna().unique()
)

print(f"Unique predicted performance ratings: {unique_predictions}")

Unique predicted performance ratings: [np.int64(2), np.int64(3), np.int64(4)]

### 10.2 Define The Potential Low-Performance Threshold

In [33]:
# Define the potential low-performance threshold

if len(unique_predictions) > 1:

    low_performance_threshold = unique_predictions[0]

else:

    low_performance_threshold = None

print(
    f"Potential low-performance threshold: "
    f"{low_performance_threshold}"
)

Potential low-performance threshold: 2

### 10.3 Identify Employees Predicted in the Lowest Performance Category

In [34]:
# Identify employees predicted in the lowest performance category

if low_performance_threshold is not None:

    potential_low_performers = prediction_results[
        prediction_results[
            "PredictedPerformanceRating"
        ] == low_performance_threshold
    ].copy()

    print(
        f"Number of employees predicted in the lowest "
        f"performance category: "
        f"{len(potential_low_performers)}"
    )

else:

    potential_low_performers = pd.DataFrame()

    print(
        f"Potential low performers could not be identified "
        f"because only one prediction class is available."
    )

Number of employees predicted in the lowest performance category: 188

### 10.4 Calculate Percentage of Potential Low performers

In [35]:
# Calculate percentage of potential low performers

if len(prediction_results) > 0:

    low_performer_percentage = (
        len(potential_low_performers)
        / len(prediction_results)
        * 100
    )

else:

    low_performer_percentage = 0

print(
    f"Potential low performers: "
    f"{len(potential_low_performers)} employees"
)

print(
    f"Percentage of potential low performers: "
    f"{low_performer_percentage:.2f}%"
)

Potential low performers: 188 employees
Percentage of potential low performers: 15.67%

### 10.5 Display Potential Lower Performers

In [36]:
# Display potential low performers

if not potential_low_performers.empty:

    if employee_id_column is not None:

        low_performer_view = potential_low_performers[
            [
                employee_id_column,
                "PredictedPerformanceRating"
            ]
        ]

    else:

        low_performer_view = potential_low_performers[
            [
                "PredictedPerformanceRating"
            ]
        ]

    print(f"Potential low performer records:")

    display(
        low_performer_view.head(20)
    )

else:

    print(f"No potential low performer records identified.")

Potential low performer records:

    EmpNumber  PredictedPerformanceRating
92   E1001171                           2
132  E1001248                           2
162  E1001293                           2
164  E1001297                           2
165  E1001300                           2
169  E1001305                           2
170  E1001306                           2
175  E1001313                           2
177  E1001315                           2
178  E1001316                           2
182  E1001322                           2
189  E1001331                           2
195  E1001346                           2
204  E1001360                           2
205  E1001361                           2
208  E1001370                           2
209  E1001372                           2
211  E1001376                           2
212  E1001379                           2
221  E1001394                           2

### Insight

The model identifies employees belonging to the lowest predicted performance category. These employees should be considered for supportive interventions rather than automatic negative decisions.

## 11. PREDICTION INTERPRETATION

The prediction output should be interpreted as a machine learning estimate based on historical patterns in the training data.
A predicted performance rating does not directly explain why an employee received that prediction. It represents the class selected by the trained model from the employee's available characteristics.

### 11.1 Calculate Overall Prediction Statistics

In [37]:
# Calculate overall prediction statistics

total_employees = len(prediction_results)

prediction_counts = (
    prediction_results[
        "PredictedPerformanceRating"
    ]
    .value_counts()
    .sort_index()
)

print(f"Total employees evaluated: {total_employees}")
print(f"Number of predicted performance categories: {len(prediction_counts)}")

for rating, count in prediction_counts.items():

    percentage = (
        count / total_employees * 100
        if total_employees > 0
        else 0
    )

    print(
        f"Performance Rating {rating}: "
        f"{count} employees "
        f"({percentage:.2f}%)"
    )

Total employees evaluated: 1200
Number of predicted performance categories: 3
Performance Rating 2: 188 employees (15.67%)
Performance Rating 3: 888 employees (74.00%)
Performance Rating 4: 124 employees (10.33%)

### Insight

The distribution of predicted performance ratings provides an overall view of how the model classifies the employee population.
The predictions should be interpreted together with model evaluation metrics from the training stage.

## 12. BUSINESS INSIGHT

The prediction results can help the organization identify patterns in expected employee performance.
Potential applications include identifying employees who may benefit from training, understanding the distribution of predicted performance levels, and supporting workforce development initiatives.

### 12.1 Generate Basic Business-Level Prediction Statistics

In [38]:
# Generate basic business-level prediction statistics

business_insights = {
    "Total Employees": total_employees,
    "Potential Low Performers": len(potential_low_performers),
    "Potential Low Performer Percentage": low_performer_percentage
}

print(f"Business prediction summary:")

for metric, value in business_insights.items():

    if isinstance(value, float):

        print(f"{metric}: {value:.2f}")

    else:

        print(f"{metric}: {value}")

Business prediction summary:
Total Employees: 1200
Potential Low Performers: 188
Potential Low Performer Percentage: 15.67

### Insight

The prediction system can support HR analytics by highlighting employee groups that may require further attention. The model should be used as a decision-support tool rather than as the sole basis for employment-related decisions.

## 13. RECOMMENDATIONS

The prediction model can be incorporated into an employee development workflow.
The recommended approach is to use predictions to trigger further investigation and support rather than treating predictions as final employee evaluations.

### 13.1 Display Recommended Business Actions

In [39]:
# Display recommended business actions

recommendations = [
    "Review employees predicted in the lower performance category.",
    "Identify training and skill-development opportunities.",
    "Discuss workload and work-environment factors where appropriate.",
    "Use multiple performance indicators instead of relying only on model predictions.",
    "Periodically retrain the model using updated and representative employee data.",
    "Monitor model performance across relevant employee groups."
]

print(f"Recommended actions:")

for index, recommendation in enumerate(
    recommendations,
    start=1
):

    print(f"{index}. {recommendation}")

Recommended actions:
1. Review employees predicted in the lower performance category.
2. Identify training and skill-development opportunities.
3. Discuss workload and work-environment factors where appropriate.
4. Use multiple performance indicators instead of relying only on model predictions.
5. Periodically retrain the model using updated and representative employee data.
6. Monitor model performance across relevant employee groups.

### Insight

The model is most useful when predictions are combined with human review, employee development programs, and other relevant organizational information.

## 14. ETHICAL CONSIDERATIONS

Employee performance prediction involves sensitive workplace decisions. A machine learning model can reproduce patterns and biases present in historical data.
Therefore, predictions should not automatically determine promotions, compensation, disciplinary actions, termination, or other high-impact employment decisions.

### 14.1 Define Ethical Considerations

In [40]:
# Define ethical considerations

ethical_considerations = [
    "Predictions should support human review rather than replace it.",
    "Historical bias in training data can affect model predictions.",
    "Sensitive employee information should be protected.",
    "Employees should not be unfairly penalized based only on predictions.",
    "Model predictions should be periodically audited for unfair outcomes.",
    "The purpose and limitations of automated predictions should be clearly documented."
]

print(f"Ethical considerations:")

for index, consideration in enumerate(
    ethical_considerations,
    start=1
):

    print(f"{index}. {consideration}")

Ethical considerations:
1. Predictions should support human review rather than replace it.
2. Historical bias in training data can affect model predictions.
3. Sensitive employee information should be protected.
4. Employees should not be unfairly penalized based only on predictions.
5. Model predictions should be periodically audited for unfair outcomes.
6. The purpose and limitations of automated predictions should be clearly documented.

### Insight

Machine learning predictions must be used responsibly. Employee performance is influenced by many factors that may not be captured in the dataset, and automated predictions can contain errors or biases.

## 15. MODEL LIMITATIONS

The prediction model has several limitations.

First, the model can only learn patterns represented in the training data. If the historical data contains bias, incomplete information, or measurement problems, those issues can influence future predictions.

Second, a prediction does not establish causation. A feature that is strongly associated with a model prediction does not necessarily cause employee performance to increase or decrease.

Third, employee behavior and organizational conditions can change over time, meaning that a model trained on historical data may become less accurate if it is not periodically evaluated and retrained.

### 15.1 Display Model Limitations

In [41]:
# Display model limitations

model_limitations = [
    "Predictions depend on the quality of the training data.",
    "Historical patterns may not represent future employee behavior.",
    "Model predictions do not establish causal relationships.",
    "Prediction errors are possible.",
    "Important employee factors may not be present in the dataset.",
    "Model performance can change when business conditions change.",
    "The model should be periodically validated and retrained."
]

print(f"Model limitations:")

for index, limitation in enumerate(
    model_limitations,
    start=1
):

    print(f"{index}. {limitation}")

Model limitations:
1. Predictions depend on the quality of the training data.
2. Historical patterns may not represent future employee behavior.
3. Model predictions do not establish causal relationships.
4. Prediction errors are possible.
5. Important employee factors may not be present in the dataset.
6. Model performance can change when business conditions change.
7. The model should be periodically validated and retrained.

### Insight

The prediction model should be treated as a decision-support system with measurable uncertainty rather than as a perfect employee evaluation mechanism.

## 16. CONCLUSION

This notebook successfully demonstrates the complete employee performance prediction workflow using the trained INX Future Inc machine learning model.

The trained model was loaded from the saved .joblib file, employee data was prepared without the target variable, performance predictions were generated, prediction probabilities were calculated where supported, employee-wise results were created, and potential low performers were identified.

The prediction system can support HR analytics and employee development by helping identify patterns that deserve further investigation. However, predictions should always be combined with human judgment, appropriate organizational context, fairness checks, and responsible handling of employee information.

### 16.1 Final Prediction Sumamry

In [43]:
# Final prediction summary

print(f"=" * 60)
print(f"INX FUTURE INC EMPLOYEE PERFORMANCE - PREDICTION SUMMARY")
print(f"=" * 60)

print(f"Total employees evaluated: {total_employees}")
print(
    f"Potential low performers identified: "
    f"{len(potential_low_performers)}"
)
print(
    f"Potential low performer percentage: "
    f"{low_performer_percentage:.2f}%"
)
print(
    f"Number of predicted performance categories: "
    f"{len(prediction_counts)}"
)

print(f"=" * 60)
print(f"Prediction workflow completed successfully.")
print(f"=" * 60)

print("\nNext Step:")

print("-" *70)
print("Visualization the Model.")

print("-" * 70)

============================================================
INX FUTURE INC EMPLOYEE PERFORMANCE - PREDICTION SUMMARY
============================================================
Total employees evaluated: 1200
Potential low performers identified: 188
Potential low performer percentage: 15.67%
Number of predicted performance categories: 3
============================================================
Prediction workflow completed successfully.
============================================================

Next Step:
----------------------------------------------------------------------
Visualization the Model.
----------------------------------------------------------------------